AllCops:
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/IndentHash:
  Enabled: false
